src/OnlineExamSystem.Web.Mvc/Controllers/ExamsController.cs
using Abp.AspNetCore.Mvc.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OnlineExamSystem.Authorization;
using OnlineExamSystem.Business.Abstract;
using OnlineExamSystem.Business.Concrete;
using OnlineExamSystem.Controllers;
using OnlineExamSystem.Data;
using OnlineExamSystem.Dtos;
using OnlineExamSystem.Users;
using System.Collections.Generic;
using System.Linq;

namespace OnlineExamSystem.Web.Controllers
{
    [AbpMvcAuthorize(PermissionNames.Pages_Exams)]
    public class ExamsController : OnlineExamSystemControllerBase
    {
        private readonly IUserAppService _userAppService;
        private readonly IExamManager _examManager;

        public ExamsController(IUserAppService userAppService, IExamManager examManager)
        {
            _userAppService = userAppService;
            _examManager = examManager;
        }

        // GET: ExamsController
        public ActionResult Index()
        {
            return View();  
        }

        // GET: ExamsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ExamsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ExamsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ExamDto examDto)
        {
            _examManager.AddExam(examDto);
            return View();
        }

        // GET: ExamsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ExamsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ExamsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ExamsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

src/OnlineExamSystem.Web.Mvc/Views/Exams/Create.cshtml
@using OnlineExamSystem.Dtos;

@model ExamDto

@{
    ViewBag.Title = "Yeni Sınav Oluştur";
}

<h2>Yeni Sınav Oluştur</h2>

@using (Html.BeginForm("Create", "Exams", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TeacherId, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.TeacherId, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.TeacherId, "", new { @class = "text-danger" })
    </div>

    <h3>Soru Listesi</h3>
    <table class="table">
        <thead>
            <tr>
                <th>Soru Metni</th>
                <th>Seçenekler</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Questions.Count; i++)
            {
                <tr>
                    <td>
                        @Html.HiddenFor(model => model.Questions[i].Text)
                        @Html.DisplayFor(model => model.Questions[i].Text)
                    </td>
                    <td>
                        @foreach (var choice in Model.Questions[i].Choices)
                        {
                            <div>
                                @Html.HiddenFor(model => model.Questions[i].Choices.ElementAt(0).Text)
                                @Html.DisplayFor(model => model.Questions[i].Choices.ElementAt(0).Text)
                                @Html.HiddenFor(model => model.Questions[i].Choices.ElementAt(0).IsCorrect)
                                @Html.DisplayFor(model => model.Questions[i].Choices.ElementAt(0).IsCorrect)
                            </div>
                            <div>
                                @Html.HiddenFor(model => model.Questions[i].Choices.ElementAt(1).Text)
                                @Html.DisplayFor(model => model.Questions[i].Choices.ElementAt(1).Text)
                                @Html.HiddenFor(model => model.Questions[i].Choices.ElementAt(1).IsCorrect)
                                @Html.DisplayFor(model => model.Questions[i].Choices.ElementAt(1).IsCorrect)
                            </div>
                            <!-- Daha fazla seçenek eklemek için gerektiği kadar bu bloğu tekrarlayabilirsiniz -->
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div class="form-group">
        <input type="submit" value="Sınavı Oluştur" class="btn btn-primary" />
    </div>
}

<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>

src/OnlineExamSystem.Web.Mvc/Views/Exams/index.cshtml
<p>AAAAAAAAAAAAAAAAAA</p>